In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.24.3


In [7]:
# 1D Array
print(np.array([1,2,3,4,5.0]))
print(np.array([1,2,3,4,5]))

#2D Array
print(np.array([[1,2,3,4],[5,6,7,8]]))

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
# create numpy array using list

L1= [1,2,3,4]
print(np.array(L1))

[1 2 3 4]


In [20]:
# matrix on ones and zeros
np.ones((3,4)) # default dtype = float
np.ones((3,4), dtype=int)

np.zeros((3,4), dtype=int)
np.zeros((3,4)).astype(int) #alternate way to define type

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
#Identity matrix
np.identity(4, int)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
#Arrange()
np.arange(5)
np.arange(10,1,-1)
#np.arange(10,1,-2)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [33]:
#Concat
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
#Attributes
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.ndim(s)) # no of axes / dim
print(np.shape(s)) # n * m matrix
print(np.size(s)) # no of elements

2
(3, 3)
9


In [51]:
#reshaping the array
A1 = np.arange(1,13)
A2 = A1.reshape((3,4))
print(A2)
A1.reshape((6,2))
A1.reshape((12,1))
#flatten to convert matrix into 1D array
print(A2.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
#Max and Min
A2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A2D)
print(A2D[1,]) # row 1
print(A2D[:,1]) # col 1
np.max(np.array([[1,2,3],[4,5,6],[7,8,9]]))
np.min(np.array([[1,2,3],[4,5,6],[7,8,9]]))

#Max and Min of each row and col
np.min(np.array([[1,2,3],[4,5,6],[7,8,9]]), axis=0) #min of each col
np.min(np.array([[1,2,3],[4,5,6],[7,8,9]]), axis=1) #min of each row

#Max and Min of particular row, 
# find min at row 1

print(min(A2D[1,]))

#Max and Min of particular col
# find min at col 1
print(min(A2D[:,1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5 8]
4
2


In [105]:
# Diagonal, trace , reverse diagonal
print(A2D)
print(A2D.diagonal())
print(A2D.trace())
print("--"*5)
print(np.fliplr(A2D))
print(np.fliplr(A2D).diagonal())
print(np.fliplr(A2D).trace())
print("--"*5)
print(np.flipud(A2D))
print(np.flipud(A2D).diagonal())
print(np.flipud(A2D).trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 5 9]
15
----------
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[3 5 7]
15
----------
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[7 5 3]
15


In [107]:
# Transpose # Rows into cols
print(A2D)
print(A2D.transpose()) # rows into cols

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [116]:
# Addition and subtraction
A2d_1 = np.arange(1,10).reshape(3,3)
A2d_2 = np.arange(11,20).reshape(3,3)
print(A2d_1)
print(A2d_2)
# Sum
print(A2d_1 + A2d_2)
# Diff
print(A2d_2 - A2d_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [118]:
# Matrix multiplication ( row * col)
print(A2d_1 @ A2d_2)
print(A2d_2 @ A2d_1)

#In matrix multiplication A@B != B@A

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[150 186 222]
 [186 231 276]
 [222 276 330]]


In [121]:
#Element by element multiplication
print(A2d_1 * A2d_2)
print(A2d_2 * A2d_1)

# A*B == B **A

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [132]:
#Indexing and slicing
print(A1)
print(A1[2])
print(A1[-1])
print(A1[:]) # Print all
print(A1[::1]) # Print all ( Default move)
print(A1[::2]) # Skip one element
print(A1[::-1]) # Reverse print
print(A1[-2:-5:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
3
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]
[12 11 10  9  8  7  6  5  4  3  2  1]
[11 10  9]


In [138]:
#Indexing - extracting elements from 2Darray
print(A2)
print(A2[0,0])
print(A2[0,3])
print(A2[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
4
12


In [145]:
# Slicing - 2Darray
A2 = np.arange(64).reshape(8,8)
print(A2)
print(A2[0:3,::]) # row 0-3 , cols all
print(A2[:,1]) # all rows , 1 cols

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[ 1  9 17 25 33 41 49 57]
