In [3]:
# Numerical python ( numpy) , homogenous values
# Written over C and hence its efficient
# 3PL
# Mostly used for Matrices

import numpy as np # Alias
print (np.__version__)

1.24.3


In [4]:
# Smallest form of matrices are arrays

A1 = np.array([1,2,3,4,5.0]) # Create matrix in py
print(A1) # A1 is a 1D array

[1. 2. 3. 4. 5.]


In [5]:
A1 = np.array([1,2,3,4,5]) # Create matrix in py
print(A1) # A1 is a 1D array

[1 2 3 4 5]


In [6]:
# Multi Dim Array ( 2 D matrix  - 3row , 4 col)

A2 = np.array([[1,2,3,4],[5,6,7,8],[2,1,3,5]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]
 [2 1 3 5]]


In [7]:
#Create np array via list

l1 = [1,2,3,4]
print(l1)

A3 = np.array(l1)
print (A3)

[1, 2, 3, 4]
[1 2 3 4]


In [8]:
#Ones()

B1 = np.ones((3,4))
print(B1) # Default float

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
B1 = np.ones((3,4), dtype=int)
print(B1) # Int matrix

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
B2 = np.zeros((3,3)).astype(int)
print(B2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
#Identity matrix - square matrix with diagonal elements are 1 and remaining are zero

print(np.identity(4).astype(int))


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# Array range()
# starts with zero and default step size = 1 
# Dimension 1 row , 5 cols
print(np.arange(5))


[0 1 2 3 4]


In [16]:
print(np.arange(10,1,-2))

[10  8  6  4  2]


In [19]:
print(np.arange(0,-10,-2))

[ 0 -2 -4 -6 -8]


In [21]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [25]:
#concat

#Vertical stack ( on top ) and horizontal stack ( side by side)

a = np.array([[1,2],[2,3],[3,4]])
b = np.array([[1,2],[2,3],[3,4]])
print(np.hstack((a,b)))

[[1 2 1 2]
 [2 3 2 3]
 [3 4 3 4]]


In [26]:
a = np.array([[1,2],[2,3],[3,4]])
b = np.array([[1,2],[2,3],[3,4]])
print(np.vstack((a,b)))

[[1 2]
 [2 3]
 [3 4]
 [1 2]
 [2 3]
 [3 4]]


In [31]:
s = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(np.ndim(s))
print(np.shape(s))
print(np.size(s))

2
(3, 3)
9


In [35]:
# Reshaping reshape(m,n) - m no of rows , n - no of cols

'''Converting 1d to 2 D array'''
A1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(A1.reshape(3,4))
print(A1.reshape(6,2))
print(A1.reshape(12,1))
print(A1.reshape(1,12))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [41]:
#Flatten() , transform to 1d array
# Used in CNN 
A1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
A2 = A1.reshape(3,4)
print(A1)
print(A2)
print(A2.flatten())


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
1
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Max and min
A1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
A2 = A1.reshape(3,4)
print(A1)
print(A2)
print(np.max(A2))
print(np.min(A2))

In [44]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
np.min(A, axis=0)
np.min(A, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 4, 7])

In [56]:
# Matrix Operations

'''
Transpose - rows into cols
Multiplication - Row * cols or Element * element 
Diagonal()
Trace() - sum of diagonal elements
Reverse diagonal - fliplr , flipup
Addition and subtraction
Multiplication a @ b (A@B is not equal to B@A) - row @ cols
Multiplication a * b - Element * element 


'''

a1 = np.arange(9).reshape(3,3)
print(a1)
a2 = np.arange(9).reshape(3,3)
print(a2)
print(a1 + a2)
print(a1 - a2)
print(a1 @ a2)
print(a2 @ a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [62]:
#Extract elements of array [ start : stop : step size]
a1 = np.arange(1,30,2)
print(a1)
print(a1[2])
print(a1[-1]) # Last element
print( a1[-2:-5:-1])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
5
29
[27 25 23]


In [65]:
#2D array - define for both rows and cols
a2 = np.arange(64).reshape(8,8)
print(a2[0:3,::]) # First 3 rows and all cols


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [71]:
#Broadcasting
#bringing smaller arry to size of larger array to perform vector and scalar ops
# Ex Matrix a + 1 ( 1 is added to all elements of matrix)
'''Broadcasting happens when they are equal, or one of them is 1.'''

a1 = np.array([1,2,3,4,5])
b1 = np.array([2])  
c1 = np.array([1,1,1])
aa1 = 2

print (a1)
print (a1.shape)
print (a1 + b1)  # Called broadcasting of b1 as b1 is stretched
print ( b1.shape)
print (b1 + c1)
print (c1.shape)

#print ( a1 + c1 ) # This is not allowed as shape doesn't match

[1 2 3 4 5]
(5,)
[3 4 5 6 7]
(1,)
[3 3 3]
(3,)


ValueError: operands could not be broadcast together with shapes (5,) (3,) 