In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
iris = pd.read_csv("iris.csv")
iris.shape
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
# input
x = iris.iloc[:, [0, 3]].values
  
# output
y = iris.iloc[:, 4].values

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [9]:
# Import the AdaBoost classifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
# Create adaboost classifer object
abc = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1), n_estimators=300)

# Train Adaboost Classifer
model1 = abc.fit(xtrain, ytrain)


#Predict the response for test dataset
y_pred = model1.predict(xtest)

C:\Users\user\anaconda3\New folder\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [10]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
cm = confusion_matrix(ytest, y_pred)
print(metrics.classification_report(ytest, y_pred, labels=["Setosa", 
"Versicolor","Virginica"]))
  
print ("Confusion Matrix : \n", cm)

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       0.93      1.00      0.96        13
   Virginica       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

Confusion Matrix : 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
